### ISSUE TITLE
Flag to only output names of repos containing matches

### ISSUE THREAD

**Issue by rnorth** [janeklb/gh-search#29]
This tool is great - it's been invaluable recently, and really makes it easier to leverage GitHub search in bigger workflows!

One suggestion: have a flag to only output the names of matching repos. This would be useful when we want to just identify repos with a particular trait, e.g. for reporting or mass clone-patch purposes.

In the spirit of `grep`'s `--files-with-matches` flag, perhaps this could be named `--repos-with-matches` or similar?

**Comment by janeklb** [comment]
Realised I forgot to document this in readme so re-opening this issue

Feature is available on [dev release](https://test.pypi.org/project/gh-search/1.0.0.dev573252591/)
```
pip install -i https://test.pypi.org/simple/ gh-search==1.0.0.dev573252591
```

**Comment by rnorth** [comment]
Awesome, thanks @janeklb. Have tested and it's working perfectly!
