### ISSUE TITLE
Better configuration management

### ISSUE THREAD

**Issue by janeklb** [janeklb/gh-search#3]
Give option to manage gh tokens and api urls in a local config file on the users file system, rather than relying on envars

**Comment by yermulnik** [comment]
Is there any progress on this?

**Comment by janeklb** [comment]
I have not made any progress, no. Wasn’t sure if there was appetite for it - envars have been working fine for me.

Are envars not suitable for you?

**Comment by yermulnik** [comment]
They are suitable but sort of less secure. I don't really want my GH Token to be set globally for the shell session via env just for a single app (`gh-search`) or to make sure I don't forget to set this envvar every time I want to use this **great** tool.
Having this set via config file is more common, imho.
Thanks

**Comment by janeklb** [comment]
Ah yes - the security aspect is a very important one. Thanks for calling it out. I will bump this issue up on my todo list (though to be transparent, it’s still not at the top).

It’s worth nothing that I’ve been less enthused to work on this tool (though I very much appreciate your comment!), ever since I found that GH is working on an improved search themselves: https://cs.github.com/

I suspect a `gh` update will follow too..

**Comment by yermulnik** [comment]
> I will bump this issue up on my todo list (though to be transparent, it’s still not at the top).

Thanks a lot!

> ever since I found that GH is working on an improved search themselves: https://cs.github.com/

This was basically how I came across `gh-search` and found it very convenient (thank you once again!).
The https://cs.github.com/ redirects me to https://github.com/ =(

> I suspect a `gh` update will follow too..

Who knows whether it's going to be as convenient and flexible as `gh-search` is =)
Anyways I'll defo will keep using `gh-search` and will keep in my arsenal of great utilities!

**Comment by janeklb** [comment]
Released in 0.8.1 https://github.com/janeklb/gh-search/releases/tag/0.8.1 :)

@yermulnik please let me know how the general UX of this feature feels when you get a chance to try it out

**Comment by yermulnik** [comment]
yay! works great! thanks a lot!

**Comment by yermulnik** [comment]
@janeklb When you wrote "Released in 0.8.1", the first thing I did was `gh-search --version`, though this failed — what would you think of adding `--version` (https://click.palletsprojects.com/en/8.0.x/api/#click.version_option)? If this looks good to you, I'll create an issue for you to keep track of the request. Let me know.

**Comment by janeklb** [comment]
Yeah, why not :) feel free to raise an issue

**Comment by yermulnik** [comment]
https://github.com/janeklb/gh-search/issues/58
