### ISSUE TITLE
Homebrew release

### ISSUE THREAD

**Issue by janeklb** [janeklb/gh-search#43]
Follow https://docs.brew.sh/Homebrew-and-Python and provide a `brew install` option for installing `gh-search`

**Comment by yermulnik** [comment]
Is there any progress on this?

**Comment by janeklb** [comment]
No progress here either. I’ve been planning to rewrite this tool in golang for a while now (which has ultimately amounted to not making progress on either front).

If there’s a lot more appetite for a brew install then I might consider it in the meantime. Though feel free to submit PRs (either here or to the official homebrew repo!)

**Comment by yermulnik** [comment]
> If there’s a lot more appetite for a brew install then I might consider it in the meantime.

That would be great. Thanks.

I seem to think this can help eliminating dependency conflicts like the https://github.com/janeklb/gh-search/issues/51 where one tool on my laptop (installed from Homebrew) requires more newer version of `click`, whilst `gh-search` hasn't bumped its requirement from an older version of `click` yet.

> Though feel free to submit PRs (either here or to the official homebrew repo!)

I'd love to but unluckily I have zero to nothing knowledge and experience creating Homebrew repos and installation configuration files 😢
